from abc import ABC
from uuid import UUID

from src.cinema_platform_django.subscription.domain.entities.subscription import (
    SubPlan,
    Subscription,
)


class SubRepositoryABC(ABC):
    def get_by_id(self, sub_id: UUID) -> Subscription | None: ...
    def get_active_for_user(self, user_id: UUID) -> Subscription | None: ...
    def create(self, sub: Subscription) -> Subscription: ...
    def update(self, sub: Subscription) -> Subscription: ...


class PlanRepositoryABC(ABC):
    def get_by_id(self, plan_id: UUID) -> SubPlan | None: ...
    def get_by_name(self, name: str) -> SubPlan | None: ...
    def get_all_active(self) -> list[SubPlan]: ...
    def create(self, plan: SubPlan) -> SubPlan: ...
    def update(self, plan: SubPlan) -> SubPlan: ...
