events {
    worker_connections 1024;
}

http {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    upstream django_backend { server django_service:8000; }
    upstream recommendation_backend { server recommendation_service:5001; }
    upstream payment_backend { server payment_service:5002; }
    upstream auth_backend { server auth_service:5003; }

    server {
        listen 80;

        location /api/v1/recommendations {
            proxy_pass http://recommendation_backend;
        }

        location /payment/ {
            proxy_pass http://payment_backend;
        }

        location /auth/ {
            proxy_pass http://auth_backend/;
        }

        location /api/v1/login {
            proxy_pass http://auth_backend/login;
        }

        location /api/v1/user {
            proxy_pass http://django_backend;
        }

        location / {
            proxy_pass http://django_backend;
        }

        location /static/ {
            alias /app/static/;
        }

        location /media/ {
            alias /app/media/;
        }
    }
}