name: Python CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main, stage]
  workflow_dispatch:

jobs:
  python-lint:
    uses: OnYyon/ci-templates/.github/workflows/python-lint.yml@main
    with:
      python-version: "3.14"
